import { jsPDF } from 'jspdf';
import type { BrandVoiceResponse } from '../types';

/**
 * Returns current local date in YYYY-MM-DD format.
 */
export function getFormattedDate(): string {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const date = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${date}`;
}

/**
 * Generates a clean, lowercase, alphanumeric-safe slug for the brand name.
 */
export function getBrandSlug(brandName: string): string {
  return brandName
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
}

class PDFBuilder {
  doc: jsPDF;
  y: number;
  margin: number;
  pageWidth: number;
  pageHeight: number;
  writableWidth: number;
  pageNum: number;

  constructor() {
    this.doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });
    this.margin = 20;
    this.pageWidth = this.doc.internal.pageSize.getWidth();
    this.pageHeight = this.doc.internal.pageSize.getHeight();
    this.writableWidth = this.pageWidth - this.margin * 2;
    this.y = this.margin;
    this.pageNum = 1;
    this.doc.setFont('helvetica', 'normal');
  }

  checkPageBreak(neededHeight: number) {
    if (this.y + neededHeight > this.pageHeight - this.margin) {
      this.drawFooter();
      this.doc.addPage();
      this.pageNum++;
      this.y = this.margin + 10;
      this.drawHeader();
    }
  }

  drawHeader() {
    this.doc.setFont('helvetica', 'oblique');
    this.doc.setFontSize(8);
    this.doc.setTextColor(148, 163, 184); // slate-400
    this.doc.text('Brand Voice Style Guide', this.margin, this.margin - 5);
    this.doc.setDrawColor(226, 232, 240); // slate-200
    this.doc.line(this.margin, this.margin - 3, this.pageWidth - this.margin, this.margin - 3);
    this.doc.setFont('helvetica', 'normal');
  }

  drawFooter() {
    this.doc.setDrawColor(226, 232, 240); // slate-200
    this.doc.line(this.margin, this.pageHeight - this.margin + 3, this.pageWidth - this.margin, this.pageHeight - this.margin + 3);

    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(8);
    this.doc.setTextColor(148, 163, 184); // slate-400
    this.doc.text('Generated by Brand Voice Generator', this.margin, this.pageHeight - this.margin + 8);
    this.doc.text(`Page ${this.pageNum}`, this.pageWidth - this.margin - 12, this.pageHeight - this.margin + 8);
  }

  drawCoverPage(brandName: string, tagline: string, modelUsed: string) {
    // left visual vertical bar
    this.doc.setFillColor(79, 70, 229); // indigo-600
    this.doc.rect(0, 0, 8, this.pageHeight, 'F');

    this.y = 50;

    // Logo placeholder
    this.doc.setDrawColor(79, 70, 229);
    this.doc.setFillColor(248, 250, 252);
    this.doc.rect(30, this.y, 45, 16, 'FD');
    this.doc.setTextColor(79, 70, 229);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(9);
    this.doc.text('[BRAND LOGO]', 30 + 10, this.y + 10);

    this.y += 35;

    // Subtitle
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(13);
    this.doc.setTextColor(100, 116, 139); // slate-500
    this.doc.text('PROFESSIONAL BRAND VOICE STYLE GUIDE', 30, this.y);

    this.y += 12;

    // Brand Title
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(36);
    this.doc.setTextColor(30, 41, 59); // slate-800
    const nameLines = this.doc.splitTextToSize(brandName, this.writableWidth - 20);
    this.doc.text(nameLines, 30, this.y);

    this.y += nameLines.length * 12 + 5;

    // Tagline
    if (tagline && tagline !== 'Not Available') {
      this.doc.setFont('helvetica', 'italic');
      this.doc.setFontSize(14);
      this.doc.setTextColor(71, 85, 105); // slate-600
      const tagLines = this.doc.splitTextToSize(`"${tagline}"`, this.writableWidth - 20);
      this.doc.text(tagLines, 30, this.y);
      this.y += tagLines.length * 6 + 15;
    } else {
      this.y += 20;
    }

    // Divider Line
    this.doc.setDrawColor(79, 70, 229);
    this.doc.setLineWidth(1);
    this.doc.line(30, this.y, 110, this.y);
    this.doc.setLineWidth(0.2); // reset

    this.y += 35;

    // Cover Meta
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(10);
    this.doc.setTextColor(100, 116, 139);
    this.doc.text('DOCUMENT SUMMARY', 30, this.y);

    this.y += 8;
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(10);
    this.doc.setTextColor(51, 65, 85);
    this.doc.text(`Date Generated:  ${getFormattedDate()}`, 30, this.y);
    this.y += 6;
    this.doc.text(`Model Engine:    ${modelUsed}`, 30, this.y);
    this.y += 6;
    this.doc.text('Format:          Interactive PDF Export v1.1', 30, this.y);

    // Page Break
    this.doc.addPage();
    this.y = this.margin + 10;
    this.drawHeader();
  }

  addHeading(text: string) {
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(16);
    this.doc.setTextColor(79, 70, 229); // indigo-600
    const lines = this.doc.splitTextToSize(text, this.writableWidth);
    const h = lines.length * 6;
    
    // Add page break if heading is too close to bottom
    this.checkPageBreak(h + 15);
    
    if (this.y > this.margin + 15) {
      this.doc.setDrawColor(241, 245, 249); // slate-100
      this.doc.line(this.margin, this.y - 4, this.pageWidth - this.margin, this.y - 4);
    }
    this.doc.text(lines, this.margin, this.y);
    this.y += h + 5;
  }

  addSubHeading(text: string) {
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(11);
    this.doc.setTextColor(71, 85, 105); // slate-600
    const lines = this.doc.splitTextToSize(text, this.writableWidth);
    const h = lines.length * 4.5;
    this.checkPageBreak(h + 4);
    this.doc.text(lines, this.margin, this.y);
    this.y += h + 2;
  }

  addParagraph(text: string) {
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(9.5);
    this.doc.setTextColor(51, 65, 85); // slate-700
    const lines = this.doc.splitTextToSize(text, this.writableWidth);
    const h = lines.length * 4.5;
    this.checkPageBreak(h + 4);
    this.doc.text(lines, this.margin, this.y);
    this.y += h + 4;
  }

  addBulletPoint(text: string) {
    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(9.5);
    this.doc.setTextColor(51, 65, 85);
    const bullet = '• ';
    const lines = this.doc.splitTextToSize(text, this.writableWidth - 5);
    const h = lines.length * 4.5;
    this.checkPageBreak(h + 3.5);
    this.doc.text(bullet, this.margin, this.y);
    this.doc.text(lines, this.margin + 4, this.y);
    this.y += h + 2;
  }

  addDivider() {
    this.checkPageBreak(6);
    this.doc.setDrawColor(241, 245, 249); // slate-100
    this.doc.line(this.margin, this.y, this.pageWidth - this.margin, this.y);
    this.y += 6;
  }

  save(filename: string) {
    this.drawFooter();
    this.doc.save(filename);
  }
}

/**
 * Builds and downloads a professional PDF guide.
 */
export function exportPDF(data: BrandVoiceResponse, modelUsed: string) {
  const builder = new PDFBuilder();
  const overview = data.brandOverview;
  const identity = data.brandIdentity;
  const guide = data.contentGuide;
  const assets = data.marketingAssets;
  const insights = data.customerInsights;

  // Draw Cover
  builder.drawCoverPage(overview.brandName, overview.tagline, modelUsed);

  // 1. BRAND OVERVIEW
  builder.addHeading('1. Brand Overview');
  builder.addSubHeading('Mission Statement');
  builder.addParagraph(overview.mission);
  builder.addSubHeading('Market Positioning & Summary');
  builder.addParagraph(overview.summary);
  builder.addDivider();

  // 2. BRAND IDENTITY
  builder.addHeading('2. Brand Identity');
  builder.addSubHeading('Target Audience Definition');
  builder.addParagraph(identity.targetAudience);

  builder.addSubHeading('Tone of Voice Traits');
  identity.tone.forEach((t) => builder.addBulletPoint(t));

  builder.addSubHeading('Writing Style Guidelines');
  identity.writingStyle.forEach((w) => builder.addBulletPoint(w));

  builder.addSubHeading('Personality Attributes');
  identity.personality.forEach((p) => builder.addBulletPoint(p));

  builder.addSubHeading('Communication Styles');
  identity.communicationStyle.forEach((c) => builder.addBulletPoint(c));

  builder.addSubHeading('Core Values');
  identity.coreValues.forEach((v) => builder.addBulletPoint(v));
  builder.addDivider();

  // 3. CONTENT GUIDE
  builder.addHeading('3. Content Guide & Writing Rules');
  builder.addSubHeading('CTA Writing Directives');
  builder.addParagraph(guide.ctaStyle);
  builder.addSubHeading('Target Reading Grade Level');
  builder.addParagraph(guide.readingLevel);

  builder.addSubHeading('Preferred Editorial Vocabulary');
  builder.addParagraph(guide.preferredWords.join(', '));

  builder.addSubHeading('Vocabulary to Avoid');
  builder.addParagraph(guide.avoidWords.join(', '));

  builder.addSubHeading('Core Writing Rules');
  guide.writingRules.forEach((r) => builder.addBulletPoint(r));
  builder.addDivider();

  // 4. MARKETING ASSETS & COPY
  builder.addHeading('4. Marketing Assets & Copy');

  const addAssetBlock = (title: string, asset: any) => {
    builder.addSubHeading(title);
    
    builder.addSubHeading('Hook Options:');
    asset.hookTitles.forEach((ht: string) => builder.addBulletPoint(ht));
    
    builder.addSubHeading('Hook Strategy & Connection:');
    builder.addParagraph(asset.hookExplanation);
    
    builder.addSubHeading('Main Script Copy:');
    builder.addParagraph(asset.script);
    
    builder.addSubHeading('Action-Oriented Call to Action:');
    builder.addParagraph(asset.cta);
    
    builder.addSubHeading('Visual Production Directions:');
    builder.addBulletPoint(`Camera Angles & Shots: ${asset.visualDirection?.cameraAngle || 'Not Available'}`);
    builder.addBulletPoint(`Lighting Style & Setup: ${asset.visualDirection?.lighting || 'Not Available'}`);
    builder.addBulletPoint(`Background & Setting: ${asset.visualDirection?.background || 'Not Available'}`);
    builder.addBulletPoint(`Dominant Color Palette: ${asset.visualDirection?.colorPalette || 'Not Available'}`);
    builder.addBulletPoint(`Sequence Flow & Product Placement: ${asset.visualDirection?.sceneFlow || 'Not Available'}`);
    
    builder.addSubHeading('Vocal Performance Cues:');
    builder.addBulletPoint(`Speaking Style: ${asset.voiceDirection?.speakingStyle || 'Not Available'}`);
    builder.addBulletPoint(`Energy Threshold: ${asset.voiceDirection?.energy || 'Not Available'}`);
    builder.addBulletPoint(`Emotion Mode: ${asset.voiceDirection?.emotion || 'Not Available'}`);
    builder.addBulletPoint(`Pacing of Delivery: ${asset.voiceDirection?.pace || 'Not Available'}`);
    builder.addBulletPoint(`Target Evoked Feeling: ${asset.voiceDirection?.targetFeeling || 'Not Available'}`);
    
    builder.addSubHeading('Suggested Hashtags:');
    builder.addParagraph(asset.hashtags.join(' '));
    builder.addDivider();
  };

  addAssetBlock('🖼️ Asset A: Image/Static Banner Ad', assets.imageAd);
  addAssetBlock('🎥 Asset B: User Generated Content (UGC)', assets.ugc);
  addAssetBlock('⚡ Asset C: Short-Form Video (TikTok/Reels)', assets.shortVideo);
  addAssetBlock('📺 Asset D: Long-Form Video (YouTube/Webinar)', assets.longVideo);

  builder.addSubHeading('General Social Media Captions');
  assets.captions.forEach((cap) => builder.addBulletPoint(cap));
  builder.addDivider();

  // 5. CUSTOMER INSIGHTS
  builder.addHeading('5. Customer Insights & Objections');
  builder.addSubHeading('Target Pain Points');
  insights.painPoints.forEach((p) => builder.addBulletPoint(p));

  builder.addSubHeading('Desired Outcomes');
  insights.desiredOutcomes.forEach((o) => builder.addBulletPoint(o));

  builder.addSubHeading('Buying Motivations');
  insights.buyingMotivations.forEach((bm) => builder.addBulletPoint(bm));

  builder.addSubHeading('Objections & Mitigation Framework');
  insights.objections.forEach((obj) => builder.addBulletPoint(obj));

  builder.addSubHeading('Target Emotional Triggers');
  insights.emotionalTriggers.forEach((et) => builder.addBulletPoint(et));
  builder.addDivider();

  // 6. STRATEGIC BRAND VOICE ANALYSIS REPORT
  const analysis = data.brandVoiceAnalysis;
  builder.addHeading('6. Strategic Brand Voice Analysis Report');
  
  builder.addSubHeading('Executive Summary');
  builder.addParagraph(analysis.executiveSummary);

  builder.addSubHeading(`Brand Voice Strength Assessment: ${analysis.voiceStrength}`);
  
  builder.addSubHeading('Brand Personality Summary');
  builder.addParagraph(analysis.personalitySummary);

  builder.addSubHeading('Key Brand Differentiators');
  analysis.keyDifferentiators.forEach((item) => builder.addBulletPoint(item));

  builder.addSubHeading('Recommended Messaging Themes (Voice Alignment)');
  analysis.recommendedMessaging.forEach((item) => builder.addBulletPoint(item));

  builder.addSubHeading('Messaging Themes to Avoid (Voice Violations)');
  analysis.avoidMessaging.forEach((item) => builder.addBulletPoint(item));

  builder.addSubHeading('Emotional Positioning Strategy');
  builder.addParagraph(analysis.emotionalPositioning);

  builder.addSubHeading('Competitive Industry Positioning');
  builder.addParagraph(analysis.competitivePosition);

  builder.addSubHeading('Recommended Next Steps (Consistency Directives)');
  analysis.recommendedNextSteps.forEach((item) => builder.addBulletPoint(item));

  // Save to file
  const brandSlug = getBrandSlug(overview.brandName);
  const dateStr = getFormattedDate();
  const filename = `${brandSlug}_brand_voice_${dateStr}.pdf`;

  builder.save(filename);
}
